baseurl = "https://spacemule.net"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = true

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # set a custom favicon (default is a `themeColor` square)
  favicon = "../favicon.ico"

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false


[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "spacemule.net"
    subtitle = "Delivering goods across inter-dimensional boundaries"
    owner = "Noah Kalish"
    keywords = "linux opensuse podman containers kubernetes k8s"
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "spacemule.net"
      logoHomeLink = "/"

    [languages.en.menu]
     [[languages.en.menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories"
	weight = 100
      [[languages.en.menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags"
	weight = 110
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About Me"
        url = "/about"
	weight = 150
      [[languages.en.menu.main]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/spacemule"
	weight = 140
      [[languages.en.menu.main]]
        identifier = "zahava"
        name = "Zahava is Cool"
        url = "https://zahava-is.cool"
	weight = 160
